#!/bin/bash
# Install xvpn for the current platform.
#
#   macOS   brew + launchd + /usr/local
#   Linux   distro package manager + systemd + /usr/local
#
# Both install the same binary and seed the same generated configs; only the
# service manager and package tooling differ.
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${PREFIX:-/usr/local}"
OS="$(uname -s)"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "$1 not found in PATH"; }

# --- dependencies ----------------------------------------------------------
# xray and sing-box are the data and ingress planes; neither is bundled.
install_deps() {
  case "$OS" in
    Darwin)
      need brew
      log "installing xray + sing-box (brew)"
      brew install xray sing-box
      ;;
    Linux)
      if command -v pacman >/dev/null 2>&1; then
        log "installing xray + sing-box (pacman)"
        sudo pacman -S --needed --noconfirm xray sing-box
      elif command -v apt-get >/dev/null 2>&1; then
        log "installing sing-box (apt); xray often needs its own repo"
        sudo apt-get install -y sing-box || \
          die "sing-box unavailable via apt — see https://sing-box.sagernet.org/installation/"
        command -v xray >/dev/null 2>&1 || \
          die "xray not found — install from https://github.com/XTLS/Xray-core#installation"
      elif command -v dnf >/dev/null 2>&1; then
        log "installing sing-box (dnf)"
        sudo dnf install -y sing-box || die "sing-box unavailable via dnf"
        command -v xray >/dev/null 2>&1 || die "xray not found in PATH"
      else
        die "no supported package manager found (pacman/apt-get/dnf)"
      fi
      ;;
    *) die "unsupported OS: $OS" ;;
  esac
}

# --- build + install binary ------------------------------------------------
log "building"
make -C "$SRC" build

log "linking into $PREFIX/bin"
sudo mkdir -p "$PREFIX/bin"
sudo ln -sf "$SRC/bin/xvpn" "$PREFIX/bin/xvpn"
# Still linked for the currently-installed launchd plist, which points at it.
# Removed once `make start` switches the service over.
[ -f "$SRC/bin/xvpn-daemon" ] && sudo ln -sf "$SRC/bin/xvpn-daemon" "$PREFIX/bin/xvpn-daemon" || true

# on.json / selective.json / xvpn.conf are generated by the binary: they depend
# on the installed sing-box schema and this host's platform.
log "seeding configs"
"$SRC/bin/xvpn" repair
[ -f "$SRC/mode" ] || echo default > "$SRC/mode"

# --- service ---------------------------------------------------------------
install_macos_service() {
  log "installing launchd agent"
  # launchd requires a root-owned real file, not a symlink.
  sudo cp "$SRC/com.xvpn.plist" /Library/LaunchDaemons/com.xvpn.plist
  sudo chown root:wheel /Library/LaunchDaemons/com.xvpn.plist
  sudo chmod 644 /Library/LaunchDaemons/com.xvpn.plist
  sudo launchctl bootout system/com.xvpn 2>/dev/null || true
  sudo rm -f /private/var/db/com.xvpn.launchd/com.xvpn.plist 2>/dev/null || true
  sudo launchctl bootstrap system /Library/LaunchDaemons/com.xvpn.plist
}

install_linux_service() {
  local unit=/etc/systemd/system/xvpn.service
  local xvpn_bin
  xvpn_bin="$(command -v xvpn || echo "$PREFIX/bin/xvpn")"

  log "installing systemd unit"
  sudo tee "$unit" >/dev/null <<EOF
[Unit]
Description=xvpn supervisor
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$xvpn_bin --supervise
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable --now xvpn.service
  sudo systemctl --no-pager status xvpn.service || true
}

install_deps
case "$OS" in
  Darwin) install_macos_service ;;
  Linux)  install_linux_service ;;
esac

cat <<EOF

installed on $OS.

  xvpn import 'vless://...'    import a link
  xvpn set default             selective routing (per app)
  xvpn apps set Telegram       route one app
  xvpn sites set netflix.com   route one site (and its subdomains)
  xvpn                         current mode + what goes via xray
  xvpn --help                  everything else
EOF