use std::env;
use std::fs;
use std::io::{self, Write};
use std::path::PathBuf;
use std::process::Command;

use serde_json::{json, Value};

fn xvpn_dir() -> PathBuf {
    if let Ok(d) = env::var("XVPN_DIR") {
        return PathBuf::from(d);
    }
    // Resolve relative to executable, following symlinks
    let exe = env::current_exe().unwrap_or_else(|_| PathBuf::from("/usr/local/bin/xvpn"));
    let real = fs::canonicalize(&exe).unwrap_or(exe);
    real.parent()
        .and_then(|p| p.parent())
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("/usr/local/etc/xvpn"))
}

fn show_ip() {
    let output = Command::new("curl")
        .args(["-4", "-s", "--max-time", "5", "ifconfig.me"])
        .output();
    match output {
        Ok(o) if o.status.success() => {
            let ip = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if !ip.is_empty() {
                println!("public IPv4: {}", ip);
            }
        }
        _ => {}
    }
}

fn show_status(d: &PathBuf) {
    let mode = fs::read_to_string(d.join("mode"))
        .unwrap_or_else(|_| "unset".into())
        .trim()
        .to_string();
    let active = fs::read_to_string("/var/run/xvpn.current")
        .unwrap_or_else(|_| "stopped".into())
        .trim()
        .to_string();
    println!("mode: {}  active: {}", mode, active);
}

fn set_mode(d: &PathBuf, mode: &str) {
    fs::write(d.join("mode"), mode).expect("Failed to write mode file");
    println!("mode: {}", mode);
    // Give daemon time to pick it up
    std::thread::sleep(std::time::Duration::from_secs(6));
    show_ip();
}

fn get_ssid() -> String {
    let output = Command::new("sh")
        .args(["-c", "networksetup -listallhardwareports | awk '/Wi-Fi/{getline; print $2}' | head -1 | xargs -I{} ipconfig getsummary {} | awk -F ' SSID : ' '/ SSID : /{print $2}'"])
        .output();
    match output {
        Ok(o) => {
            let ssid = String::from_utf8_lossy(&o.stdout).trim().to_string();
            match ssid.as_str() {
                "" | "<redacted>" => String::new(),
                s => s.to_string(),
            }
        }
        _ => String::new(),
    }
}

fn get_gw_mac() -> String {
    let output = Command::new("sh")
        .args(["-c", "IF=$(networksetup -listallhardwareports | awk '/Wi-Fi/{getline; print $2}' | head -1); GW=$(route -n get -ifscope $IF default 2>/dev/null | awk '/gateway/{print $2}'); [ -n \"$GW\" ] && arp -n $GW | awk '{print $4}'"])
        .output();
    match output {
        Ok(o) => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        _ => String::new(),
    }
}

fn read_conf(d: &PathBuf) -> (Vec<String>, Vec<String>) {
    let content = fs::read_to_string(d.join("xvpn.conf")).unwrap_or_default();
    let mut ssids = Vec::new();
    let mut macs = Vec::new();
    for line in content.lines() {
        if line.starts_with("SELECTIVE_SSIDS=") {
            ssids = parse_array(line);
        } else if line.starts_with("SELECTIVE_GWMACS=") {
            macs = parse_array(line);
        }
    }
    (ssids, macs)
}

fn parse_array(line: &str) -> Vec<String> {
    let start = line.find('(').map(|i| i + 1).unwrap_or(0);
    let end = line.rfind(')').unwrap_or(line.len());
    line[start..end]
        .split('"')
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string())
        .collect()
}

fn write_conf(d: &PathBuf, ssids: &[String], macs: &[String]) {
    let content = format!(
        "# xvpn.conf — generated by `xvpn use`\nSELECTIVE_SSIDS=({})\nSELECTIVE_GWMACS=({})\n",
        ssids.iter().map(|s| format!("\"{}\"", s)).collect::<Vec<_>>().join(" "),
        macs.iter().map(|s| format!("\"{}\"", s)).collect::<Vec<_>>().join(" "),
    );
    fs::write(d.join("xvpn.conf"), content).expect("Failed to write xvpn.conf");
}

fn do_use(d: &PathBuf) {
    let ssid = get_ssid();
    let mac = get_gw_mac();
    let (mut ssids, mut macs) = read_conf(d);
    ssids.push(ssid.clone());
    macs.push(mac.clone());
    write_conf(d, &ssids, &macs);
    let display = if ssid.is_empty() { "(hidden)".to_string() } else { ssid };
    println!("Added: SSID='{}' gateway MAC='{}'", display, mac);
}

fn do_forget(d: &PathBuf) {
    let ssid = get_ssid();
    let mac = get_gw_mac();
    let (ssids, macs) = read_conf(d);
    let mut new_ssids = Vec::new();
    let mut new_macs = Vec::new();
    for i in 0..ssids.len() {
        if ssids[i] != ssid && macs.get(i).map(|m| m != &mac).unwrap_or(true) {
            new_ssids.push(ssids[i].clone());
            new_macs.push(macs[i].clone());
        }
    }
    write_conf(d, &new_ssids, &new_macs);
    let display = if ssid.is_empty() { "(hidden)".to_string() } else { ssid };
    println!("Removed: SSID='{}' gateway MAC='{}'", display, mac);
}

fn edit_selective_json(d: &PathBuf, action: &str, app: &str) {
    let path = d.join("selective.json");
    let content = fs::read_to_string(&path).expect("Failed to read selective.json");
    let mut cfg: Value = serde_json::from_str(&content).expect("Failed to parse selective.json");

    let regex = format!(".*/{}\\\\.app/.*", app.replace('.', "\\\\."));

    // DNS rules
    if let Some(dns_rules) = cfg.get_mut("dns").and_then(|v| v.get_mut("rules")).and_then(|v| v.as_array_mut()) {
        if action == "add" {
            let exists = dns_rules.iter().any(|r| {
                r.get("process_path_regex")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().any(|p| p.as_str().map(|s| s.contains(&regex)).unwrap_or(false)))
                    .unwrap_or(false)
            });
            if !exists {
                dns_rules.push(json!({"process_path_regex": [regex], "server": "remote"}));
                println!("Added {}", app);
            } else {
                println!("{} already exists", app);
            }
        } else {
            dns_rules.retain(|r| {
                !r.get("process_path_regex")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().any(|p| p.as_str().map(|s| s.contains(&regex)).unwrap_or(false)))
                    .unwrap_or(false)
            });
            println!("Removed {}", app);
        }
    }

    // Route rules
    if let Some(route_rules) = cfg.get_mut("route").and_then(|v| v.get_mut("rules")).and_then(|v| v.as_array_mut()) {
        if action == "add" {
            let exists = route_rules.iter().any(|r| {
                r.get("process_path_regex")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().any(|p| p.as_str().map(|s| s.contains(&regex)).unwrap_or(false)))
                    .unwrap_or(false)
            });
            if !exists {
                route_rules.push(json!({"process_path_regex": [regex], "outbound": "xray"}));
            }
        } else {
            route_rules.retain(|r| {
                !r.get("process_path_regex")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter().any(|p| p.as_str().map(|s| s.contains(&regex)).unwrap_or(false)))
                    .unwrap_or(false)
            });
        }
    }

    fs::write(&path, serde_json::to_string_pretty(&cfg).unwrap()).expect("Failed to write selective.json");
}

fn list_apps(d: &PathBuf) {
    let content = fs::read_to_string(d.join("selective.json")).expect("Failed to read selective.json");
    let cfg: Value = serde_json::from_str(&content).expect("Failed to parse selective.json");

    let mut apps: Vec<String> = Vec::new();
    for section in ["dns", "route"] {
        if let Some(rules) = cfg.get(section).and_then(|v| v.get("rules")).and_then(|v| v.as_array()) {
            for rule in rules {
                if let Some(pats) = rule.get("process_path_regex").and_then(|v| v.as_array()) {
                    for pat in pats {
                        if let Some(p) = pat.as_str() {
                            // Extract app name from regex like ".*/AppName\\.app/.*"
                            // Find the last '/' before '.app' and extract what's between
                            if let Some(app_start) = p.rfind('/') {
                                let after_slash = &p[app_start + 1..];
                                if let Some(app_end) = after_slash.find(".app") {
                                    let name = &after_slash[..app_end];
                                    // Remove any trailing backslash
                                    let name = name.trim_end_matches('\\');
                                    if !name.is_empty() && !apps.contains(&name.to_string()) {
                                        apps.push(name.to_string());
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    println!("Apps routed through xray in default mode:");
    if apps.is_empty() {
        println!("  (none)");
    } else {
        apps.sort();
        for app in apps {
            println!("  - {}", app);
        }
    }
}

fn do_import(d: &PathBuf, link: Option<&str>) {
    let link = match link {
        Some(l) => l.to_string(),
        None => {
            print!("Paste vless:// link: ");
            io::stdout().flush().unwrap();
            let mut input = String::new();
            io::stdin().read_line(&mut input).expect("Failed to read input");
            input.trim().to_string()
        }
    };

    if !link.starts_with("vless://") {
        eprintln!("Error: not a vless:// link");
        std::process::exit(1);
    }

    // Parse the vless link
    let parsed = parse_vless_link(&link);
    let out_path = d.join("xray.json");
    let json_str = serde_json::to_string_pretty(&parsed).expect("Failed to serialize");
    fs::write(&out_path, json_str).expect("Failed to write xray.json");

    // Set permissions
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&out_path, fs::Permissions::from_mode(0o600));
    }

    println!("Wrote {}", out_path.display());

    // Validate with xray
    let output = Command::new("xray")
        .args(["run", "-test", "-c"])
        .arg(&out_path)
        .output();
    match output {
        Ok(o) if o.status.success() => {
            println!("Config OK. Daemon reloads automatically.");
        }
        Ok(o) => {
            eprintln!("xray validation failed:");
            eprintln!("{}", String::from_utf8_lossy(&o.stderr));
            std::process::exit(1);
        }
        Err(e) => {
            eprintln!("Failed to run xray: {}", e);
            std::process::exit(1);
        }
    }
}

fn parse_vless_link(link: &str) -> Value {
    use std::collections::HashMap;

    // Parse URL manually since we don't have urlparse
    let rest = &link[8..]; // strip "vless://"
    let (userinfo, host_part) = rest.split_once('@').unwrap_or((rest, ""));
    let (host_port, query) = host_part.split_once('?').unwrap_or((host_part, ""));
    let (host, port) = host_port.rsplit_once(':').unwrap_or((host_port, "443"));
    let port: u16 = port.parse().unwrap_or(443);

    let mut params: HashMap<String, String> = HashMap::new();
    if !query.is_empty() {
        for pair in query.split('&') {
            if let Some((k, v)) = pair.split_once('=') {
                params.insert(k.to_string(), url_decode(v));
            }
        }
    }

    let net = params.get("type").cloned().unwrap_or_else(|| "tcp".into());
    let sec = params.get("security").cloned().unwrap_or_else(|| "none".into());

    let mut user = json!({
        "id": url_decode(userinfo),
        "encryption": params.get("encryption").cloned().unwrap_or_else(|| "none".into()),
    });
    if let Some(flow) = params.get("flow") {
        user["flow"] = json!(flow);
    }

    let mut stream = json!({
        "network": net,
        "security": sec,
    });

    if sec == "reality" {
        let mut reality = json!({
            "serverName": params.get("sni").cloned().unwrap_or_default(),
            "publicKey": params.get("pbk").cloned().unwrap_or_default(),
            "shortId": params.get("sid").cloned().unwrap_or_default(),
            "fingerprint": params.get("fp").cloned().unwrap_or_else(|| "chrome".into()),
        });
        if let Some(spx) = params.get("spx") {
            reality["spiderX"] = json!(spx);
        }
        stream["realitySettings"] = reality;
    } else if sec == "tls" {
        let mut tls = json!({
            "serverName": params.get("sni").cloned().unwrap_or_else(|| host.to_string()),
            "fingerprint": params.get("fp").cloned().unwrap_or_else(|| "chrome".into()),
        });
        if let Some(alpn) = params.get("alpn") {
            tls["alpn"] = json!(alpn.split(',').map(|s| s.to_string()).collect::<Vec<_>>());
        }
        stream["tlsSettings"] = tls;
    }

    if net == "ws" {
        let mut ws = json!({
            "path": url_decode(&params.get("path").cloned().unwrap_or_else(|| "/".into())),
        });
        if let Some(host) = params.get("host") {
            ws["headers"] = json!({"Host": host});
        }
        stream["wsSettings"] = ws;
    } else if net == "grpc" {
        stream["grpcSettings"] = json!({
            "serviceName": params.get("serviceName").cloned().unwrap_or_default(),
        });
    } else if net == "xhttp" || net == "splithttp" {
        let mut x = json!({
            "path": url_decode(&params.get("path").cloned().unwrap_or_else(|| "/".into())),
        });
        if let Some(host) = params.get("host") {
            x["host"] = json!(host);
        }
        if let Some(mode) = params.get("mode") {
            x["mode"] = json!(mode);
        }
        stream["xhttpSettings"] = x;
    }

    json!({
        "log": {"loglevel": "warning"},
        "inbounds": [
            {"listen": "127.0.0.1", "port": 10808, "protocol": "socks", "settings": {"udp": true}},
            {"listen": "127.0.0.1", "port": 10809, "protocol": "http"},
        ],
        "outbounds": [
            {
                "tag": "proxy",
                "protocol": "vless",
                "settings": {"vnext": [{"address": host, "port": port, "users": [user]}]},
                "streamSettings": stream,
            },
            {"tag": "direct", "protocol": "freedom"},
        ],
    })
}

fn url_decode(s: &str) -> String {
    let mut result = String::new();
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '%' {
            let mut hex = String::new();
            if let Some(h1) = chars.next() {
                hex.push(h1);
            }
            if let Some(h2) = chars.next() {
                hex.push(h2);
            }
            if let Ok(byte) = u8::from_str_radix(&hex, 16) {
                result.push(byte as char);
            }
        } else {
            result.push(c);
        }
    }
    result
}

fn show_help() {
    println!("xvpn — xray VPN manager");
    println!();
    println!("USAGE");
    println!("  xvpn <command> [args]");
    println!();
    println!("COMMANDS");
    println!("  on                  Route everything through xray (global mode)");
    println!("  default             Route only listed apps through xray (selective mode)");
    println!("  import [link]       Import a vless:// link (prompts if omitted)");
    println!("  use                 Register current Wi-Fi for default mode");
    println!("  forget              Remove current Wi-Fi from default mode");
    println!("  add <app>           Add an app to default-mode routing (e.g. xvpn add Telegram)");
    println!("  remove <app>        Remove an app from default-mode routing");
    println!("  apps                List apps in default-mode routing");
    println!("  status              Show current mode and daemon state");
    println!();
    println!("EXAMPLES");
    println!("  xvpn import");
    println!("  xvpn on");
    println!("  xvpn default");
    println!("  xvpn add Telegram");
    println!("  xvpn add \"Visual Studio Code\"");
}

fn main() {
    let args: Vec<String> = env::args().collect();
    let d = xvpn_dir();

    let command = args.get(1).map(|s| s.as_str()).unwrap_or("status");

    match command {
        "on" | "default" | "off" => set_mode(&d, command),
        "import" => do_import(&d, args.get(2).map(|s| s.as_str())),
        "use" => do_use(&d),
        "forget" => do_forget(&d),
        "add" => {
            let app = args.get(2).expect("Usage: xvpn add <app-name>");
            edit_selective_json(&d, "add", app);
        }
        "remove" => {
            let app = args.get(2).expect("Usage: xvpn remove <app-name>");
            edit_selective_json(&d, "remove", app);
        }
        "apps" => list_apps(&d),
        "status" => show_status(&d),
        "help" | "-h" | "--help" => show_help(),
        _ => {
            eprintln!("Unknown command: {} (try: xvpn help)", command);
            std::process::exit(1);
        }
    }
}
